version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "3100:3100"
    environment:
      YOUR_API: "http://your_api:8000"

  thirdpartymock:
    build: ./thirdpartymock
    ports:
      - "3000:3000"

  your_api:
    build: ./your_api
    volumes:
      - ./your_api:/app
    ports:
      - "8000:8000"
    command: uvicorn testing:app --host 0.0.0.0 --reload